feat: login 구현
TeamRuneat/react_basic pull request #17
Opened 2023-06-24 12:35 UTC by lee-jooyeon

제플린에 올라온 디자인에 맞춰서 로그인 모달창 구현했습니다.
저번에 말한 폴더구조 한번 변경해봤는데 피드백 부탁드립니다,,, 
수정해야할 거 있으면 말씀해주세요!!

2023-06-24 16:11 UTC, extracold1209 requested changes
제가 빌드테스트때문에 바로 main 으로 푸시한게 있었는데 반영이 잘 되어있네요 ㅎㅎ;  
감사합니다

디렉토리 구조가 변경되면서 1 depth 에 모든 컴포넌트가 계속 늘어나는 부분은 막은 것 같습니다. 👍   
하지만 pages, components 가 둘 다 depth 가 생기면서 어떤건 컴포넌트고, 어떤건 페이지인가? 가 모호해지는게 아닐까 싶은데요.

- pages 에 들어가는 것은 route 가 보여주어야할 가장 큰 단위의 컴포넌트 하나.
- components 는 Page component 안에 포함되는 나머지 컴포넌트들

로 나누면 더 보기 좋지 않을까 싶습니다

2023-06-24 16:11 UTC, extracold1209 commented on src/components/common/Navbar.jsx
> +  if(location.pathname === '/login'){
Navbar 가 /login 인 경우에만 컴포넌트 자체가 노출하지 않게 하고 있는데,

아마 다른 path 에서도 Navbar 를 노출하고 싶지 않다면 여기서 계속 분기가 늘어날 것 같은 구조가 되지 않을까 싶어요.

그렇다면 Navbar 는 '내가 노출되어야 하는가를 알 필요 없이, 부모쪽 (Page 단위라면 Router 에서, 각 컴포넌트라면 부모 컴포넌트에서) 에서 제어하는 건 어떨까 싶습니다

2023-06-24 16:11 UTC, extracold1209 commented on src/components/login/KakaoLoginButton.jsx
> +const KAKAO_AUTH_URL = `https://kauth.kakao.com/oauth/authorize?client_id=${REST_API_KEY}&redirect_uri=${REDIRECT_URI}&response_type=code`;
ㅠㅠ 죄송합니다 작업이 늦어지고 있네요..  
현재 백엔드에서는

- GET /auth 요청시 ; client_id, response_type 이 전부 포함된 주소를 리다이렉트 할 수 있도록 제공
- 카카오로 시작하기 -> /auth/callback 을 요청
- /auth/callback 은 서버에 있는 주소이며 아래의 순서대로 정보를 처리한다
  - /auth/callback 과 함께 받은 code 로 유저정보를 파악
  - 유저 세션을 생성하고, 카카오토큰-유저정보를 세션에 저장
  - set-cookie: 세션쿠키 가 포함된 redirect '/' 로 응답

- 유저는 /auth -> (302) 카카오가입화면 -> /auth/callback -> (302) /, 로그인쿠키 포함 순으로 '가입화면' 을 빼고 전부 자동이동

이 순으로 개발 예정입니다.  
그리고 이 구조가 되면 웹클라에서는 위 상수 전부 제거될 수 있습니다

2023-06-24 16:11 UTC, extracold1209 commented on src/index.css
> +@import url('https://webfontworld.github.io/BMJua/BMJua.css');
요건.. 어디인가요?

2023-06-24 16:11 UTC, extracold1209 commented on src/pages/shop/index.jsx
> +export default function AllShop(){
여기가 굉장히 헷갈릴 수 있을 것 같아요

- pages/shop/index.jsx = AllShop
- AllShop has Shop[]

이 구조만 보면 AllShop 이 무엇을 의미하는지 잘 모르겠습니다. Shop 또한 이름만 보면 모델을 말하는건지, 뷰를 말하는건지 알기 어렵지 않을까 싶어요 ㅠㅠ

pages/shop/index.jsx 는 실제로 부를때도 `import AllShop from './shop'` 이런 형태가 되는데,

- All 이라는 단어보다는 ...List ...s 이런 식의 이름이 더 보편적으로 쓰이기 좋을 것 같습니다
- pages/shop/Shop.jsx 는 결국 component 가 될텐데, pages 디렉토리에 포함되는 게 조금 어색해 보입니다
- `ShopListPage` has `ShopListItem (다른 위치)` 이런식으로 구성해도 괜찮을 것 같고, 보기 편하고 이해하기 좋은 구조라면 어떻게 되더라도 좋지만 동일한 규칙을 지니는게 포인트가 될 것 같아요

2023-06-24 16:11 UTC, extracold1209 commented on src/components/common/Navbar.jsx
> +      <h1 className='px-10 py-7 text-2xl'>
구조상 문제는 아닌데, h1 이 해당 라인 전체를 덮고있어서, Navbar 전체가 pointer 커서가 되더라구요 ㅠㅠ 조정이 필요할 것 같네요

2023-06-24 16:11 UTC, extracold1209 commented on src/components/common/Navbar.jsx
> +        {!user &&  <button onClick={() => setOpenModal(true)}>로그인</button>}
요기 마크업이 안들어가서 그런지 로그인을 클릭하기 너무 좁은것 같습니다 ㅎㅎ  
더 넓으면 좋지 않을까요..? 정확히 로그인 글자를 클릭해야만 넘어가더라구요.

![image](https://github.com/TeamRuneat/react_basic/assets/40051225/756c36e6-51de-4e67-9d36-95d8818afd24)

2023-06-25 10:39 UTC, lee-jooyeon commented on src/components/login/KakaoLoginButton.jsx
> +const KAKAO_AUTH_URL = `https://kauth.kakao.com/oauth/authorize?client_id=${REST_API_KEY}&redirect_uri=${REDIRECT_URI}&response_type=code`;
작업 시 참고하겠습니다

2023-06-25 10:39 UTC, lee-jooyeon commented on src/index.css
> +@import url('https://webfontworld.github.io/BMJua/BMJua.css');
index.css페이지인데 글꼴 추가하고 css 수정했습니다!
아직 디자인에서 나온 게 없어서 글꼴 추가외에는 한 게 딱히 없습니다.

2023-06-25 10:40 UTC, lee-jooyeon commented on src/components/common/Navbar.jsx
> +      <h1 className='px-10 py-7 text-2xl'>
핫,, 수정하겠습니다

2023-06-25 10:41 UTC, lee-jooyeon commented on src/components/common/Navbar.jsx
> +        {!user &&  <button onClick={() => setOpenModal(true)}>로그인</button>}
앗! 수정하였습니다

2023-06-25 10:42 UTC, lee-jooyeon commented on src/pages/shop/index.jsx
> +export default function AllShop(){
폴더 구조가 은근 헷갈리네여,,,,, 말씀해주신 거 참고하여 수정했습니다!

2023-06-25 10:44 UTC, lee-jooyeon commented on src/components/common/Navbar.jsx
> +  if(location.pathname === '/login'){
일단 저 코드는 필요 없어서 삭제하였습니다!

2023-06-25 14:01 UTC, extracold1209 commented on src/index.css
> +@import url('https://webfontworld.github.io/BMJua/BMJua.css');
앗 아녀 webfontworld.github.io/BMJua 라는 위치가 처음보는곳이라서요 ㅎㅎ  어디서 얻은 소스인가 싶어서 여쭤봤습니다

2023-06-25 14:15 UTC, extracold1209 approved these changes
👍 👍

2023-06-25 15:30 UTC, extracold1209 commented on src/components/login/KakaoLoginButton.jsx
> +const KAKAO_AUTH_URL = `https://kauth.kakao.com/oauth/authorize?client_id=${REST_API_KEY}&redirect_uri=${REDIRECT_URI}&response_type=code`;
너무 늦은시간이라 나중에 톡으로 말씀드릴게요 ㅠㅠ
서버에 최소기능으로 카카오 로그인 기능을 배포했습니다.

- GET /auth : 호출하면 자동으로 가입하기 화면으로 넘어갑니다.
- GET /auth/callback : 가입하기 화면이 자동으로 호출합니다. 서버에서 로직을 처리하기위한 용도이고 즉시 / 로 이동합니다
  - 이동위치가 따로 필요하면 말씀해주세요.
  - 따로 필요할 때가 있는 이유는, 특정 위치로 이동하고 흰 화면일때 클라이언트에서 로직을 처리하고, 원하는 화면으로 라우팅 할 수 있는 권한을 가져갈 수 있기 때문입니다. 홈화면으로 이동하는것으로 문제 없다면 상관없습니다
- GET /auth/user : 카카오 유저의 정보가 내려옵니다.

**그냥 순서대로 호출하면 됩니다. 다음 회의때 말씀드릴게요**  
**고도화가 필요합니다. 왜냐면 지금은 /auth 가 곧 로그인까지 하고있어서요**

2023-06-26 14:47 UTC, merged