Feature/svg icon
TeamRuneat/react_basic pull request #33
Opened 2023-10-01 14:57 UTC by lee-jooyeon

svg 아이콘을 원래 img 태그에 박아서 사용했었는데 svg 태그를 사용하여 관리할 수 있도록 수정하였습니다.
svg icon들을 종류별로 svg sprite로 만들어서 SVG 컴포넌트로 사용할 수 있습니다.

2023-10-03 09:47 UTC, extracold1209 reviewed
SocialSVG, LogoSVG, CommonSVG 라는 컴포넌트가 있고, 이들은 href 를 만들어주는 역할이 각자 다른 것 같네요

그런데 컴포넌트의 구조는 전부 동일하니까 한번 더 나눌 수 있지 않을까 싶어요

```tsx
type Props = {
  type: 'social' | 'common' | 'logo'
  id: string;
  width: number;
  height: number;
}

const SVG: React.FC<Props> = ({id, type, width, height}) => {
  return (
    <svg role='img' width={width} height={height}>
      <use href={`${type}#${id}`} />
    </svg>
  )
}

export default SVG;
```

2023-10-08 16:27 UTC, lee-jooyeon commented
수정했습니다!!

2023-10-09 12:41 UTC, extracold1209 requested changes
엄.. 이렇게 된다면 CommonSVG = LogoSVG = SocialSVG 인데, 사용처에서 이걸 나누는 의미가 있을까요? 의미구분을 위해 아직 나눠둔 상태라 하더라도 동일한 구조의 다른 컴포넌트들이 생성되게 되기때문에 불필요한 계층화라고 보여집니다

2023-10-10 12:57 UTC, lee-jooyeon commented
오,, 한번 더 나누라는 의미를 잘못 이해한 거 같네요,, 공통으로 쓸 수 있는 컴포넌트 하나만 남기고 다시 수정했습니다.

2023-10-11 11:58 UTC, merged